[clustering]
first_year = 2006
last_year = 2019
clustering_years = 10
n_clusters = 4

[io]
data_dir = data
# either 'bw' or 'color' (default: 'bw')
color = bw
clustering_schema = clustering
nephropathy_table = nephropathy
retinopathy_table = retinopathy

[database]
dbname = datiamdlavoro
user =     omissis
password = omissis
host =     omissis
port =     omissis